#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <output directory>"
    echo
    echo "Note: the output directory should be writable from the nodes in the Hadoop cluster, e.g. a directory on NFS."
    exit 1
fi

OUTPUT_DIR=$1

zip -r tiles.zip tiles/ && \
spark-submit --master yarn-cluster --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.enabled=true --py-files tiles.zip subtile_average.py "$OUTPUT_DIR"

